version: '3.8'

services:
  ds-server-principal:
    build: .
    ports:
      - "8000:50051"  # Ajusta el puerto según tu aplicación
    volumes:
      - ./Server:/usr/src/app  # Monta el directorio de la aplicación
      - /usr/src/app/__pycache__  # Evita que el directorio __pycache__ del host sobrescriba el del contenedor
    environment:
      - PYTHONUNBUFFERED=1  # Opcional: mejora la salida de logs
    tty: true         # Asignar una terminal para la interacción
  ds-server:
    build: .
    volumes:
      - ./Server:/usr/src/app  # Monta el directorio de la aplicación
      - /usr/src/app/__pycache__  # Evita que el directorio __pycache__ del host sobrescriba el del contenedor
    environment:
      - PYTHONUNBUFFERED=1  # Opcional: mejora la salida de logs
    tty: true         # Asignar una terminal para la interacción
