# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: communication.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\x12\x12TagBasedFileSystem\"\x17\n\x07TagList\x12\x0c\n\x04tags\x18\x01 \x03(\t\"6\n\x08TagQuery\x12\x12\n\ntags_query\x18\x01 \x03(\t\x12\x16\n\x0eoperation_tags\x18\x02 \x03(\t\"-\n\x0b\x46ileContent\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"J\n\nFilesToAdd\x12.\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x1f.TagBasedFileSystem.FileContent\x12\x0c\n\x04tags\x18\x02 \x03(\t\"3\n\x0fOperationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x0c\x46ileLocation\x12\x11\n\tfile_hash\x18\x01 \x01(\t\x12\x15\n\rlocation_hash\x18\x02 \x01(\x05\"f\n\x0f\x46ileGeneralInfo\x12\r\n\x05title\x18\x01 \x01(\t\x12\x32\n\x08location\x18\x02 \x01(\x0b\x32 .TagBasedFileSystem.FileLocation\x12\x10\n\x08tag_list\x18\x03 \x03(\t2\xe5\x03\n\tClientAPI\x12J\n\x04list\x12\x1b.TagBasedFileSystem.TagList\x1a#.TagBasedFileSystem.FileGeneralInfo0\x01\x12P\n\x0b\x66ileContent\x12 .TagBasedFileSystem.FileLocation\x1a\x1f.TagBasedFileSystem.FileContent\x12O\n\x08\x61\x64\x64\x46iles\x12\x1e.TagBasedFileSystem.FilesToAdd\x1a#.TagBasedFileSystem.OperationResult\x12L\n\x07\x61\x64\x64Tags\x12\x1c.TagBasedFileSystem.TagQuery\x1a#.TagBasedFileSystem.OperationResult\x12J\n\x06\x64\x65lete\x12\x1b.TagBasedFileSystem.TagList\x1a#.TagBasedFileSystem.OperationResult\x12O\n\ndeleteTags\x12\x1c.TagBasedFileSystem.TagQuery\x1a#.TagBasedFileSystem.OperationResultB6\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_TAGLIST']._serialized_start=43
  _globals['_TAGLIST']._serialized_end=66
  _globals['_TAGQUERY']._serialized_start=68
  _globals['_TAGQUERY']._serialized_end=122
  _globals['_FILECONTENT']._serialized_start=124
  _globals['_FILECONTENT']._serialized_end=169
  _globals['_FILESTOADD']._serialized_start=171
  _globals['_FILESTOADD']._serialized_end=245
  _globals['_OPERATIONRESULT']._serialized_start=247
  _globals['_OPERATIONRESULT']._serialized_end=298
  _globals['_FILELOCATION']._serialized_start=300
  _globals['_FILELOCATION']._serialized_end=356
  _globals['_FILEGENERALINFO']._serialized_start=358
  _globals['_FILEGENERALINFO']._serialized_end=460
  _globals['_CLIENTAPI']._serialized_start=463
  _globals['_CLIENTAPI']._serialized_end=948
# @@protoc_insertion_point(module_scope)
